### ISSUE TITLE
Edit Functionality Needs Fixed 

### ISSUE THREAD

**Issue by UofMBryce** [UofMBryce/R.O.S.E#9]
I might be doing something wrong, but it appears our edit recipe function doesn't work. I ran some tests and after I altered the values in the activity, the recipe object that gets made from the new input information has the same attributes as the recipe before editing. I might not have it set up right but just in case it needs looked at

**Comment by JiqingDai** [comment]
fixed, reason for not saving into database is didn't read input value after input has changed.
